{
 "title": "SLO Dashboard",
 "description": "Tracks service's SLO and error budget consumption.",
 "time": { "from": "now-28d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "service_requests_error_count",
    "query": "${VAR_SERVICE_REQUESTS_ERROR_COUNT}"
   },
   {
    "name": "service_requests_total_count",
    "query": "${VAR_SERVICE_REQUESTS_TOTAL_COUNT}"
   },
   { "name": "alerts_filter_criteria", "query": "${VAR_ALERTS_FILTER_CRITERIA}" },
   { "name": "service_slo_target", "query": "${VAR_SERVICE_SLO_TARGET}" },
   { "name": "error_budget", "query": "${VAR_ERROR_BUDGET}" }
  ]
 },
 "panels": [
  {
   "title": "SLO Dashboard",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(ALERTS{alertstate=\"firing\",$alerts_filter_criteria}[5m])"
    }
   ]
  },
  {
   "title": "Error Budget Left",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "28 * 24 * ($error_budget - sum(rate($service_requests_error_count[28d])) by (job) / sum(rate($service_requests_total_count[28d])) by (job))"
    }
   ]
  },
  {
   "title": "Current SLO",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - sum(rate($service_requests_error_count[28d])) by (job) / sum(rate($service_requests_total_count[28d])) by (job)"
    }
   ]
  },
  {
   "title": "28 Day Window SLO",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "$service_slo_target", "legendFormat": "target" },
    {
     "expr": "(1 - sum(rate($service_requests_error_count[28d])) by (job) / sum(rate($service_requests_total_count[28d])) by (job)) * 100",
     "legendFormat": "real"
    }
   ]
  },
  {
   "title": "Probe Error Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate($service_requests_error_count[1m])) by (job) / sum(rate($service_requests_total_count[1m])) by (job)",
     "legendFormat": "error ratio"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate($service_requests_total_count[1m])) by (job)",
     "legendFormat": "total requests rate"
    },
    {
     "expr": "sum(rate($service_requests_error_count[1m])) by (job)",
     "legendFormat": "error responses rate"
    }
   ]
  }
 ]
}